### ISSUE TITLE
Tie data descriptions to dataset images

### ISSUE THREAD

**Issue by EvanBianco** [agile-geoscience/rocky-playground#13]
Right now there is no way to know which set of points belong to which dataset. The names and descriptions of the data sets are only given in the text section at the bottom of the app and there is no link to the scatter plots above. There needs to be a better connection between the scatter plots and these descriptions. For instance, each data set could be given a title (say instead of the word OUTPUT above the main heatmap), or we could place thumbnails beside the description paragraphs near the bottom. Other ideas welcome.

**Comment by kwinkunks** [comment]
There is a `title` text, which you can read if you hover over the thumbnails. But I agree it could be a lot more obvious. 

I tried to be somewhat descriptive, but you should check to see that the existing text maps reasonable well to the descriptions.

And/or you could add the thumbnails to the descriptions I guess. Shouldn't be too hard (famous last words).

**Comment by kwinkunks** [comment]
The thumbnails would be ideal, but they have to be live and the styling is a pain.

**Comment by kwinkunks** [comment]
Fixed in 9180211a5e78d6cfb4bab04bd1931815494a9bfc
